services:
  - type: web
    name: lemon-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: new-training-492518-ece3e9916ad5.jason
        sync: false
      - key: 1R-zWdM1bIMPA3rnwoGZ4qvmSVhCXeH2a5JQ3JR4JiAM
        sync: false
